language: java

sudo: required

services:
  - docker


jdk:
  - oraclejdk8

script:
  - mvn clean package
  - docker build -t craftsmenlabs/kafka-admin-rest-api:latest target/

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD2"
  - docker push craftsmenlabs/kafka-admin-rest-api:latest